# Generated by Django 2.2.4 on 2020-02-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bytecode', models.FileField(upload_to='media/')),
                ('abi', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Landlord'), (2, 'Tenant')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=50)),
                ('abi', models.CharField(max_length=47)),
                ('current', models.IntegerField(choices=[(0, 'Terminated'), (1, 'Active'), (2, 'Passive')])),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_contracts', to='buyerseller.Stakeholder')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_contracts', to='buyerseller.Stakeholder')),
            ],
        ),
    ]
